android {
    namespace = "com.ankeyboard.app"
    compileSdk = 36
    
    useLibrary 'org.apache.http.legacy'
    
    defaultConfig {
        applicationId = "com.ankeyboard.app"
        minSdk = 23
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        manifestPlaceholders = [license: 'LGPL-3.0', licenseUrl: 'https://www.gnu.org/licenses/lgpl-3.0.html']
    }
    
    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles.add(getDefaultProguardFile('proguard-android-optimize.txt'))
            proguardFiles.add('proguard-rules.pro')
        }
    }
    
    buildFeatures {
        viewBinding = true
    }
    
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    lint {
        abortOnError = false
        checkReleaseBuilds = false
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.preference:preference:1.2.1'
    
    implementation 'com.google.android.material:material:1.12.0'
    
    implementation 'com.squareup.okhttp3:okhttp:5.3.2'
    implementation 'com.squareup.retrofit2:retrofit:2.10.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.10.0'
    
    implementation 'com.google.code.gson:gson:2.10.1'
    
    implementation 'com.google.android.gms:play-services-base:18.3.0'
    
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.10.0'
    implementation 'androidx.lifecycle:lifecycle-livedata:2.10.0'
    
    implementation 'androidx.room:room-runtime:2.8.4'
    annotationProcessor 'androidx.room:room-compiler:2.8.4'

    implementation 'org.jetbrains.kotlin:kotlin-stdlib:2.3.10'
}
